import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          Homepage(),
        ]),
      ),
    );
  }
}

class Homepage extends StatelessWidget {
  const Homepage({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.00, -1.00),
              end: Alignment(0, 1),
              colors: [Color(0xFFBE05FF), Colors.white],
            ),
            boxShadow: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 4,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              const Positioned(
                left: 27,
                top: 34,
                child: Text(
                  'X GLASSES',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 24,
                    fontFamily: 'Rubik Bubbles',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 136,
                child: SizedBox(
                  width: 315,
                  height: 367,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        const TextSpan(
                          text: 'THE SUN IS GONE BUT WE HAVE THE ',
                          style: TextStyle(
                            color: Color(0xFF020CFB),
                            fontSize: 56,
                            fontFamily: 'Rubik',
                            fontWeight: FontWeight.w800,
                          ),
                        ),
                        WidgetSpan(
                          child: ShaderMask(
                            shaderCallback: (Rect bounds) {
                              return LinearGradient(
                                begin: Alignment.centerLeft,
                                end: Alignment.centerRight,
                                colors: <Color>[
                                  Colors.yellow.shade700,
                                  Colors.yellow.shade100
                                ],
                                tileMode: TileMode.repeated,
                              ).createShader(bounds);
                            },
                            child: const Text(
                              'LIGHT',
                              style: TextStyle(
                                fontSize: 56,
                                fontFamily: 'Rubik',
                                fontWeight: FontWeight.w800,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                    textAlign: TextAlign.center,
                  ),
                ),
              ),
              const Positioned(
                left: 154,
                top: 640,
                child: Text(
                  'Discounts',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF020CFB),
                    fontSize: 20,
                    fontFamily: 'Roboto Flex',
                    fontWeight: FontWeight.w300,
                    decoration: TextDecoration.underline,
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 550,
                child: SizedBox(
                  width: 310,
                  height: 43,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 310,
                          height: 43,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFEAFF00),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                            shadows: const [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 4,
                                offset: Offset(0, 4),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 115,
                        top: 10,
                        child: Text(
                          'Buy Now',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 20,
                            fontFamily: 'Roboto Flex',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
